name: GitHub actions
run-name: ${{github.actor}} has triggered the pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  run-app:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Install jdk
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "zulu"
      - name: Show Java version
        run: "java -version"
      - name: Show directory
        run: "pwd"
      - name: Install Dependencies
        run: "mvn compile"
      - name: Build application
        run: "mvn package -Dskiptests"
      - name: Test application
        run: "mvn test"
